- lib/app.dart
- lib/commands/base_command.dart
- lib/commands/refresh_command.dart
- lib/features/library/library_view.dart
- lib/main.dart
This PR fixes the example state management.
> State management

- lib/app.dart
- lib/controller/firebase_controller.dart
- lib/controller/library_controller.dart
- lib/data/user_data.dart
- lib/features/library/library_view.dart
- lib/features/library/library_view_controller.dart
- lib/model/user_model.dart
- lib/service/firebase_service.dart
- pubspec.lock
- pubspec.yaml
- test/mock_firebase_service.dart
- test/unit_test.dart
- test/widget_test.dart
More tests still need to be written
Example usage inspired by [codewithandrea](https://codewithandrea.com/videos/flutter-state-management-riverpod/):
```dart
// In app.dart file
onGenerateRoute: (RouteSettings routeSettings) {
return MaterialPageRoute<void>(
settings: routeSettings,
builder: (BuildContext context) {
...
return I18n(child: AuthChecker(child: page));
},
);
},
// Create auth_checker.dart widget
class AuthChecker extends ConsumerWidget {
const AuthChecker({Key key, required Widget child}) : super(key: key);
final Widget child;
@override
Widget build(BuildContext context, WidgetRef ref) {
final userStreamAsyncValue = ref.watch(authStateChangesProvider);
return userStreamAsyncValue.when(
data: (user) {
if (user == null) {
// Route to login screen
return LoginScreen();
}
// …
```
> Firebase Controller and Tests

- pubspec.lock
- pubspec.yaml
- test/mock_firebase_service.dart
- test/unit_test.dart
This refactors the tests for login and logout. I have not figured out how to test firebase signup yet
> Refactor unit tests

- README.md
- lib/features/library/library_view.dart
- pubspec.lock
- pubspec.yaml
- test/unit_test.dart
- test/widget_test.dart
- test_driver/app.dart
- test_driver/app_test.dart
Run with `flutter drive --target=test_driver/app.dart`
Read more about integration tests [here](https://flutter.dev/docs/cookbook/testing/integration/introduction)
> Add Integration Test

- lib/controller/firebase_controller.dart
- lib/features/library/library_view.dart
- lib/features/profile/edit_profile_view.dart
- lib/features/profile/profile_view.dart
- lib/features/profile/widgets/profile_widget.dart
- lib/model/user_model.dart
- lib/service/base_firebase_service.dart
- lib/service/firebase_service.dart
- pubspec.yaml
- test/mock_firebase_service.dart
> Realtime user data

- lib/controller/firebase_controller.dart
- lib/features/library/library_view.dart
- lib/features/library/library_view_controller.dart
- lib/features/library/series_view.dart
- lib/features/library/widgets/add_book_button.dart
- lib/features/library/widgets/add_to_collection_button.dart
- lib/features/library/widgets/item_list_tile_widget.dart
- lib/features/library/widgets/profile_button.dart
- lib/service/base_firebase_service.dart
- lib/service/firebase_service.dart
- test/mock_firebase_service.dart
Note that this overrides the collections of the book.
Also, if no collections are selected and "Move" is pressed, it will not modify the items
> Move to collection and create collection

- lib/controller/firebase_controller.dart
- lib/service/base_firebase_service.dart
- lib/service/firebase_service.dart
- test/mock_firebase_service.dart
Closes #45 
Adds book title and authors to filename to prevent conflicts between different books with the same filename
> Improve Unique Filenames

- lib/controller/firebase_controller.dart
- lib/features/auth/auth_checker.dart
- lib/features/library/library_view_controller.dart
- lib/model/user_model.dart
- lib/service/firebase_service.dart
- test/mock_firebase_service.dart
> Firestore realtime updates stop working after logout login

- lib/features/reader/book_reader_view.dart
This PR adds a back button to the reader and moves the table of contents button to the right side of the app bar.
> Add back button to reader (temp solution)

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- ios/Podfile
- ios/Runner/Info.plist
- lib/app.dart
- lib/features/in_app_update/data/update_data.dart
- lib/features/in_app_update/data/update_info.dart
- lib/features/in_app_update/update.dart
- lib/features/in_app_update/update_parser.dart
- lib/features/in_app_update/update_prompter.dart
- lib/features/in_app_update/util/common.dart
- lib/features/in_app_update/util/http_utils.dart
- lib/features/in_app_update/util/toast_utils.dart
- lib/features/widgets/init_widget.dart
- lib/main.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- update/update.json
This adds the ability to update the app from inside the app without using the playstore (Android only)
Most of the code is from: https://github.com/xuexiangjys/flutter_app_update_example
It uses this package: https://pub.dev/packages/flutter_update_dialog
> In app update

- lib/features/auth/reset_password_view.dart
- lib/features/library/library_view.dart
- lib/features/library/widgets/add_new_collection_button.dart
- lib/features/library/widgets/add_to_collection_button.dart
- lib/features/library/widgets/merge_to_series.dart
- lib/features/profile/edit_profile_view.dart
- lib/features/profile/profile_view.dart
- lib/features/profile/widgets/change_password_button.dart
- lib/features/profile/widgets/log_out_button.dart
- Empty collections are now hidden
- The collection header is hidden if there is only one collection visible
Closes #41
> Hide Empty Collections

- lib/app.dart
- lib/controller/storage_controller.dart
- lib/data/constants.dart
- lib/features/library/library_view.dart
- lib/features/library/library_view_controller.dart
- lib/features/library/series_view.dart
- lib/features/library/widgets/delete_button.dart
- lib/features/library/widgets/item_list_tile_widget.dart
- lib/features/widgets/init_widget.dart
- lib/service/storage_service.dart
Delete downloaded books with delete button when selecting books
Read downloaded books and store in Hive box
Update box when a book is downloaded or deleted
> Delete Downloaded Books

- lib/app.dart
- pubspec.yaml
> Fix error shown to screen when user isn't logged in #74

- lib/controller/firebase_controller.dart
- lib/controller/storage_controller.dart
- lib/data/constants.dart
- lib/data/user_data.dart
- lib/features/library/library_view.dart
- lib/features/library/library_view_controller.dart
- lib/features/library/series_view.dart
- lib/features/library/widgets/delete_button.dart
- lib/features/widgets/init_widget.dart
- lib/model/queue_model.dart
- lib/model/user_model.dart
- lib/service/firebase_service_storage_mixin.dart
- lib/service/storage_service.dart
- test/mock_firebase_service.dart
See #42 for details
Added StorageController.deleteItemsPermanently
> Delete items permanently

- lib/controller/firebase_controller.dart
- lib/features/auth/login_view.dart
- lib/features/auth/register_view.dart
- lib/features/library/library_view.dart
- lib/features/library/library_view_controller.dart
- lib/features/library/widgets/add_book_button.dart
- lib/features/library/widgets/add_new_collection_button.dart
- lib/features/library/widgets/add_to_collection_button.dart
- lib/features/library/widgets/delete_button.dart
- lib/features/library/widgets/item_list_tile_widget.dart
- lib/features/profile/edit_profile_view.dart
- lib/features/profile/profile_view.dart
- lib/features/profile/widgets/log_out_button.dart
remove collection feature
`FirebaseController.removeCollection`
> remove collection

- lib/controller/firebase_controller.dart
- lib/features/library/library_view.dart
- lib/features/library/library_view_controller.dart
- lib/features/library/series_view.dart
- lib/service/firebase_service.dart
> Unmerge Series Functionality

- lib/features/in_app_update/update.dart
- lib/features/library/library_view.dart
- lib/features/library/widgets/overflow_library_appbar_popup_menu_button.dart
- lib/features/library/widgets/overflow_popup_menu_button.dart
> Remove Downloads and Permanently Delete Library Items Popup Menu Button

- lib/controller/storage_controller.dart
- lib/data/user_data.dart
- lib/features/library/library_view.dart
- lib/features/library/library_view_controller.dart
- lib/features/library/widgets/overflow_library_appbar_popup_menu_button.dart
- lib/service/storage_service.dart
> Add button to queue download for multiple books

- lib/controller/firebase_controller.dart
- lib/data/constants.dart
- lib/features/library/data/book_collection.dart
- lib/features/library/library_view.dart
- lib/features/library/library_view_controller.dart
- lib/features/library/widgets/add_to_collection_button.dart
- lib/service/firebase_service.dart
- test/mock_firebase_service.dart
> [Feature] Allow merging series with series and book

- lib/controller/firebase_controller.dart
- lib/controller/storage_controller.dart
- lib/service/firebase_service_storage_mixin.dart
> Fix error that pops up when deleting a book that isn't downloaded

- lib/controller/firebase_controller.dart
- lib/controller/storage_controller.dart
- lib/data/constants.dart
- lib/features/library/library_view.dart
- lib/features/library/library_view_controller.dart
- lib/features/library/series_view.dart
- lib/features/library/widgets/overflow_library_appbar_popup_menu_button.dart
- lib/model/queue_model.dart
- lib/model/user_model.dart
- lib/service/firebase_service_storage_mixin.dart
- lib/service/storage_service.dart
> Add selecting app bar to series view

- lib/features/library/data/collection_section.dart
- lib/features/library/library_view.dart
- lib/features/library/widgets/section_widget.dart
- pubspec.lock
- pubspec.yaml
Collections can now be collapsed.
This also fixes bug #30.
Note that this removes the feature that hides the collection header if it is the only collection visible
Closes #30
> [Feature] Collections are now collapsible

- lib/controller/firebase_controller.dart
- lib/data/constants.dart
- lib/features/library/library_view_controller.dart
- lib/features/library/series_view.dart
- lib/features/library/widgets/item_list_tile_widget.dart
- lib/features/library/widgets/overflow_library_appbar_popup_menu_button.dart
unmerge updated in series view and circular popup menu
> Unmerge Button in Series App Bar

- lib/controller/firebase_controller.dart
- lib/features/in_app_update/util/toast_utils.dart
- lib/features/library/data/collection_section.dart
- lib/features/library/library_view.dart
- lib/features/library/library_view_controller.dart
- lib/features/library/widgets/add_new_collection_button.dart
- lib/features/library/widgets/add_to_collection_button.dart
- lib/features/library/widgets/section_widget.dart
- lib/service/firebase_service.dart
**Remove collection Pop up item button**
Closes #80
> Remove collection button

- lib/controller/storage_controller.dart
- lib/features/library/library_view_controller.dart
- lib/model/queue_model.dart
- lib/service/storage_service.dart
- pubspec.yaml
> Fix delete downloads button and app deleting books on app launch

- lib/features/auth/auth_checker.dart
- lib/features/widgets/init_widget.dart
The app was stuck on a loading screen while launching the app while offline.
updateDownloadedFilesProvider is now done in the background instead of showing a loading screen.
Error logging has also been added for the init widgets
Closes #106
> Fix Launching While Offline
